name: Update Google Scholar Citations

on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-citations:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Set 15-minute timeout
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        cd google_scholar_crawler
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Update citation count
      env:
        GOOGLE_SCHOLAR_ID: EqemKYsAAAAJ
      run: |
        cd google_scholar_crawler
        timeout 10m python main.py || echo "Crawling failed - keeping existing data"
        
    - name: Copy results to google-scholar-stats
      run: |
        if [ -f "google_scholar_crawler/results/gs_data_shieldsio.json" ]; then
          cp google_scholar_crawler/results/gs_data_shieldsio.json google-scholar-stats/gs_data_shieldsio.json
          echo "New citation data copied successfully"
        else
          echo "No new data available, keeping existing data"
        fi
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add google-scholar-stats/gs_data_shieldsio.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update Google Scholar citations [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push 
          echo "Changes committed and pushed successfully"
        fi 